### ISSUE TITLE
how to reset Eaz evaluation 30 days?

### ISSUE THREAD

**Issue by Charltsing** [Plot1337/EazTrialRemover#2]
after 30 days ,Eaz can not use

**Comment by ldstr** [comment]
You can use a Eaz activator

**Comment by Charltsing** [comment]
> You can use a Eaz activator

Do you have a download link for it?
I can not find it on google

**Comment by ldstr** [comment]
https://hardcracked.com/previous/eazfuscator-net/79060/13

**Comment by Charltsing** [comment]
it is not license

maybe it is virus

**Comment by Charltsing** [comment]
> 

do you have another link?

**Comment by ldstr** [comment]
I don't sorry. But you can manually load these pre-generated license files in `C:\Users\%USER%\AppData\Local\Gapotchenko`; https://anonfiles.com/Hct8Q8B1y7/Eazfuscator.NET_zip

Extract the zip in the `Gapotchenko` directory; if you already have one `Eazfuscator.NET` directory, delete it and replace it with the one in the zip archive.

You can also uninstall Eaz, remove its data (which can be found in the AppData directories), and then reinstall to reset the 30 days trial period.

Hope that helped!

**Comment by ldstr** [comment]
~~EDIT: I've noticed that in the latest update of Eaz, the activator no longer works because it remotely validates the local license. Also, removing the local AppData files doesn't work either. I'll post an update when I can.~~

**Comment by ldstr** [comment]
UPDATE: Please ignore the previous post; everything works fine in this update. However, if you need to update to a newer version of Eaz, you would need to uninstall Eaz first, then reinstall. Everything works as expected.
