### ISSUE TITLE
PatchVoidMethod Fail in WPF Application

### ISSUE THREAD

**Issue by yFlameBR** [Plot1337/EazTrialRemover#4]
Soo, i obfuscated my WPF App with Eazfuscator 2022.2.755 and it fails in PatchVoidMethod part.

I tried to use the first release one, and it kinda works, but the App doesnt open.

Output:

Found check method: 0x02000035
Patched check method!
Failed to patch!
Task completed in 0,2407635 seconds!

Im not using PE Verify.

Edit:
Also im using .Net Framework 4.7.2

Edit 2:
I also tried 2022.2.751 and 2022.1.493

**Comment by ldstr** [comment]
Can you provide instructions to replicate this error?

**Comment by yFlameBR** [comment]
> Can you provide instructions to replicate this error?

I really idk if is smth in my computer, cuz i tried in console app and didn't work too.

Here is all the settings i used:

encrypt symbol names with password
type renaming pattern
string encryption
code control flow obfuscation
encrypt resources [compress]
encrypt serializable symbol names with password
apply to type *: apply to member * when method or constructor: virtualization
virtualization

btw, ill test without any settings to see if is a problem in settings

**Comment by yFlameBR** [comment]
I tested without any settings in console app and worked, but when i tested without any settings in WPF it fails in patch void method. I think your eaz trial remover don't have support for wpf or smth like that.

**Comment by yFlameBR** [comment]
Also, when i use code control flow obfuscation in console app it fails in patchvoidmethod, without code control flow obfuscation it works

**Comment by ldstr** [comment]
Perhaps it's because you are using code control flow obfuscation. With regards to WPF, I'll look into that.

**Comment by ldstr** [comment]
This should be fixed in the [latest release](https://github.com/Plot1337/EazTrialRemover/releases).
