### ISSUE TITLE
Not work with class library

### ISSUE THREAD

**Issue by Roseclear** [Plot1337/EazTrialRemover#5]
When I try to use it to remove trial in class library, it does not work but when I change it console application, it works perfectly

**Comment by HillCat** [comment]
could you please offer the  Eazfuscator.NET 2022.2 version ,now offical web site need to lisense key to download old version. my email:caianhua#gmail.com  ,thanks very much ,I only use for study only.

**Comment by ldstr** [comment]
This should be fixed in the [latest release](https://github.com/Plot1337/EazTrialRemover/releases).
