### ISSUE TITLE
Programs ，line：82

### ISSUE THREAD

**Issue by Charltsing** [Plot1337/EazTrialRemover#7]
v1.1 fix Programs.cs
line 82 : if (patchedCheck && patchedVoid) Save(module, path);
fix:     if (patchedCheck || patchedVoid) Save(module, path);

v1.0.0.0 works fine

**Comment by Charltsing** [comment]
2023.1.427 nop the first if of the entry point,  you can skip the trial check. 
In addition to checking the date, the new version also checks whether the registry has a key value

**Comment by ldstr** [comment]
This should be fixed in the [latest release](https://github.com/Plot1337/EazTrialRemover/releases).
